### Aula 03

Introdução a aula 03
- Biblioteca Pandas
- Biblioteca NumPy
--
```python
print("Olá Mundo")
```

1. Conhecendo a biblioteca
2. Executando comandos
3.

In [1]:
import pandas as pd
import numpy as np

In [2]:
precos_produtos = [10,5,7,100]
quantidade_produtos = [3,5,6,10]

array_quantidade = np.array(quantidade_produtos)
array_produtos = np.array(precos_produtos)

faturamento = array_produtos * array_quantidade
print(faturamento)

[  30   25   42 1000]

In [3]:
precos_produtos = [10,5,7,100]
quantidade_produtos = [3,5,6,10]
nomes_produtos = ["Pastel", "Caçulinha", "Refrigerante", "Combos"]

array_quantidade = np.array(quantidade_produtos)
array_produtos = np.array(precos_produtos)

faturamento = array_produtos * array_quantidade

for nome, preco in zip(nomes_produtos, faturamento):
    print(f"{nome}: {preco}")

Pastel: 30
Caçulinha: 25
Refrigerante: 42
Combos: 1000

### Exercício de Fixação
- Criar uma lista que irá possuir 10 nomes de produtos.
- Criar uma lista que irá possuir o preço de custo (Atacado).
- Criar uma lista que irá possuir o preço de venda (Varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [4]:
produtos_nome = ["Vinho", "Macarrão","Farofa", "Conhaque", "Refrigerante","Alho","Cerveja", "Café","Estrogonofe","Fini"]
produtos_atac = [139.0, 2.49, 6.89, 5.99, 4.99, 13.90, 4.59, 16.99, 19.19, 7.12]
produtos_var = [169.0, 2.79, 7.89, 6.99, 5.59, 14.90, 6.09, 24.99, 23.99, 9.49]

nomes_array = np.array(produtos_nome) # Não tem necessidade de criar array com essa lista, pois não irá ser utilizado em cálculo.
atacado_array = np.array(produtos_atac)
varejo_array = np.array(produtos_var)

lucro = varejo_array - atacado_array
print(lucro)
print(np.sum(lucro))
print("--" * 40)
i = 0
for nome, custo, venda in zip(nomes_array, atacado_array, varejo_array):
    lucro = venda - custo
    print(f" | {i} | {nome:<12} | teve lucro de {lucro:.2f} |")
    i = i + 1
print("--" * 40)

[30.    0.3   1.    1.    0.6   1.    1.5   8.    4.8   2.37]
50.56999999999999
--------------------------------------------------------------------------------
 | 0 | Vinho        | teve lucro de 30.00 |
 | 1 | Macarrão     | teve lucro de 0.30 |
 | 2 | Farofa       | teve lucro de 1.00 |
 | 3 | Conhaque     | teve lucro de 1.00 |
 | 4 | Refrigerante | teve lucro de 0.60 |
 | 5 | Alho         | teve lucro de 1.00 |
 | 6 | Cerveja      | teve lucro de 1.50 |
 | 7 | Café         | teve lucro de 8.00 |
 | 8 | Estrogonofe  | teve lucro de 4.80 |
 | 9 | Fini         | teve lucro de 2.37 |
--------------------------------------------------------------------------------

## Pandas

In [5]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head() #Por padrão exibe as 5 primeiras informações.

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [6]:
df.tail()

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [7]:
#Dimensões
df.shape

(40, 6)

In [8]:
#Exibe as colunas na base de dados
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [10]:
#Contar valores duplicados
df.duplicated().sum()

np.int64(0)

In [11]:
#Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [12]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

Subir a base de dados
- Mostrar os 5 primeiros registros
- Mostrar os 5 últimos
- Mostrar o tamanho
- Mostrar a descrição

In [13]:
df1 = pd.read_csv(r".\data\dataset_techshop_vendas.csv")
df1.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [14]:
df1.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [15]:
df1.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [16]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [17]:
df1.shape

(800, 7)

In [24]:
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [25]:
df.notnull().sum() # Procura por valores não nulos e soma eles

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [ ]:
# Registros de temperatura
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [ ]:
#Combinando filtros
df[["id_registro","temperatura_c","falha"]]

    id_registro  temperatura_c  falha
0             1          72.62      0
1             2          81.65      0
2             3          68.87      0
3             4          66.84      0
4             5          66.23      0
5             6          64.79      0
6             7          85.02      1
7             8          60.31      0
8             9          75.84      0
9            10          68.38      1
10           11          76.31      0
11           12          74.79      0
12           13          76.31      0
13           14          63.28      0
14           15          64.98      0
15           16          81.48      0
16           17          79.62      1
17           18          69.80      0
18           19          77.16      0
19           20          73.30      1
20           21          79.77      0
21           22          71.76      0
22           23          74.16      0
23           24          74.69      1
24           25          74.03      1
25           26          75.96      0
26           27          60.80      0
27           28          69.37      1
28           29          70.28      0
29           30          73.53      0
30           31          63.59      1
31           32          68.91      0
32           33          77.62      1
33           34          73.32      1
34           35          78.24      0
35           36          68.47      0
36           37          75.62      1
37           38          78.50      0
38           39          76.19      1
39           40          68.64      0

In [32]:
#Criar uma nova coluna relacionando dados
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"Temperatura Alta", "Temperatura Baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,Temperatura Baixa
1,2,Usinagem,81.65,34.08,128,0,Temperatura Alta
2,3,Usinagem,68.87,39.44,159,0,Temperatura Baixa
3,4,Usinagem,66.84,34.52,98,0,Temperatura Baixa
4,5,Usinagem,66.23,31.57,94,0,Temperatura Baixa

In [48]:
df_ordenado = df.sort_values(by="producao_dia", ascending=False)
df_ordenado.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
2,3,Usinagem,68.87,39.44,159,0,Temperatura Baixa
30,31,Montagem,63.59,42.29,159,1,Temperatura Baixa
26,27,Usinagem,60.80,37.18,159,0,Temperatura Baixa
34,35,Usinagem,78.24,31.93,158,0,Temperatura Alta
31,32,Inspeção,68.91,32.66,155,0,Temperatura Baixa