## N-Gramas (n-grams)

In [25]:
frase = "Águias observam montanhas enquanto cientistas desenvolvem algoritmos robustos inspirando comunidades curiosas mediante colaboração ética constante produzindo descobertas úteis diariamente felizes."

In [26]:
# O split transforme a frase ou qualquer texto em uma lista.
palavras = frase.split()
palavras

['Águias',
 'observam',
 'montanhas',
 'enquanto',
 'cientistas',
 'desenvolvem',
 'algoritmos',
 'robustos',
 'inspirando',
 'comunidades',
 'curiosas',
 'mediante',
 'colaboração',
 'ética',
 'constante',
 'produzindo',
 'descobertas',
 'úteis',
 'diariamente',
 'felizes.']

In [27]:
import pandas as pd

tabela = pd.DataFrame({"palavras":palavras})
tabela

       palavras
0        Águias
1      observam
2     montanhas
3      enquanto
4    cientistas
5   desenvolvem
6    algoritmos
7      robustos
8    inspirando
9   comunidades
10     curiosas
11     mediante
12  colaboração
13        ética
14    constante
15   produzindo
16  descobertas
17        úteis
18  diariamente
19     felizes.

In [28]:
tabela["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

       palavras proxima_palavra
0        Águias        observam
1      observam       montanhas
2     montanhas        enquanto
3      enquanto      cientistas
4    cientistas     desenvolvem
5   desenvolvem      algoritmos
6    algoritmos        robustos
7      robustos      inspirando
8    inspirando     comunidades
9   comunidades        curiosas
10     curiosas        mediante
11     mediante     colaboração
12  colaboração           ética
13        ética       constante
14    constante      produzindo
15   produzindo     descobertas
16  descobertas           úteis
17        úteis     diariamente
18  diariamente        felizes.
19     felizes.             NaN

In [29]:
tabela = tabela.dropna()
tabela

       palavras proxima_palavra
0        Águias        observam
1      observam       montanhas
2     montanhas        enquanto
3      enquanto      cientistas
4    cientistas     desenvolvem
5   desenvolvem      algoritmos
6    algoritmos        robustos
7      robustos      inspirando
8    inspirando     comunidades
9   comunidades        curiosas
10     curiosas        mediante
11     mediante     colaboração
12  colaboração           ética
13        ética       constante
14    constante      produzindo
15   produzindo     descobertas
16  descobertas           úteis
17        úteis     diariamente
18  diariamente        felizes.

In [34]:
filtro = tabela["palavras"] == "Águias"
tabela[filtro]

  palavras proxima_palavra
0   Águias        observam

In [31]:
tabela[filtro]["palavras"].value_counts()

Series([], Name: count, dtype: int64)

In [32]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

Series([], Name: proportion, dtype: float64)

In [35]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'observam'