In [341]:
arquivo = open(r".\data\dom_casmurro.txt",encoding="utf-8")

texto = arquivo.read()
len(texto)

381375

In [342]:
palavras = texto.split()
len(palavras)

65708

In [343]:
import pandas as pd

tabela = pd.DataFrame({"palavras":palavras})
tabela

       palavras
0           DOM
1      CASMURRO
2           POR
3       MACHADO
4            DE
...         ...
65703         É
65704      bem,
65705         e
65706         o
65707    resto?

[65708 rows x 1 columns]

In [344]:
tabela["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65703         É            bem,
65704      bem,               e
65705         e               o
65706         o          resto?
65707    resto?             NaN

[65708 rows x 2 columns]

In [345]:
tabela = tabela.dropna()
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65702   CXLVIII               É
65703         É            bem,
65704      bem,               e
65705         e               o
65706         o          resto?

[65707 rows x 2 columns]

In [ ]:
#filtro = tabela["palavras"] == f"{tabela[filtro]["proxima_palavra"].value_counts().idxmax()}"
#tabela[filtro]["proxima_palavra"].value_counts().idxmax()
filtro = tabela["palavras"] == f"casa"

'me'

In [363]:
tabela[filtro]["palavras"].value_counts()

palavras
não    1152
Name: count, dtype: int64

In [348]:
tabela[filtro]["proxima_palavra"].value_counts()

proxima_palavra
minha       47
rua         13
nossa       12
casa,       11
morte        8
            ..
de           1
Capitú       1
casca.       1
missa        1
infancia     1
Name: count, Length: 393, dtype: int64

In [352]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'de'